<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section title_Principal Panel</name>
   <tag></tag>
   <elementGuidId>c12f4937-b326-492c-9819-f40ab6fa90f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='pp-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>efde07dd-f7b0-4bde-9ddb-4fd415b22a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-container</value>
      <webElementGuid>3c7b1179-75bd-417a-92ac-b6a5d015e5df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>property</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>f2005cf5-1ee1-48c6-826d-6e8415471492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-p-h2 col-sm-10</value>
      <webElementGuid>28fc2f5a-3856-41cf-a3f8-bac4055ce5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Principal Panel - Container Label</value>
      <webElementGuid>3d1790ac-ca12-4a82-b789-5cf055fc17be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-container&quot;)</value>
      <webElementGuid>459834db-a29f-4e50-a8ea-041cd387e008</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='pp-container']</value>
      <webElementGuid>511d310a-ad94-4d7a-a97a-6193b92da43e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/h2</value>
      <webElementGuid>3bc8590a-f142-4baa-b038-fc642091c8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'pp-container' and (text() = 'Principal Panel - Container Label' or . = 'Principal Panel - Container Label')]</value>
      <webElementGuid>3feac46f-50f8-4861-974f-5c116ca782a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
