<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section title_Principal Panel FR</name>
   <tag></tag>
   <elementGuidId>45572add-e2ac-498d-a3b1-73baf25b477c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='pp-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>5f0243c7-536f-4733-9388-131d3f8f4621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-container</value>
      <webElementGuid>a6b6704e-8436-4976-88a9-51271b06abf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>property</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>a394812c-6c9b-4945-bd40-0a0dfde588bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-p-h2 col-sm-10</value>
      <webElementGuid>7133f7b8-87e5-437e-ab28-d4825464c097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aire d’affichage principale</value>
      <webElementGuid>bb71d8c9-7628-4696-bd8e-f2e3a569e93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-container&quot;)</value>
      <webElementGuid>3a2a7dbe-f00e-44ef-86a1-799ba429f17e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='pp-container']</value>
      <webElementGuid>dbe8d0e3-a331-45e7-9b1c-1c618358b3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/h2</value>
      <webElementGuid>f1aff50d-aaad-4f09-8c32-f24d4f821b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'pp-container' and (text() = 'Aire d’affichage principale' or . = 'Aire d’affichage principale')]</value>
      <webElementGuid>73104c34-77e9-48cb-a693-a949dad30eeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
